### ISSUE TITLE
Bluespace harpoon teleports user into objects

### ISSUE THREAD

**Issue by Wutnold124** [Cherkir/Alien-Isolation-13#39]
Using the bluespace harpoon has a chance for you to literally teleport inside of objects. First time it happened to me I teleported inside of a space cleaner bottle. Second time, I teleported inside of god knows what. Third time, I teleported inside of a pipe. All three of those times an admin had to teleport me out. To replicate it, just use the bluespace harpoon a lot, and you might teleport inside of something.

**Comment by Alexshreds** [comment]
can you like, not like, even read like the previous issues, like omg

**Comment by Wutnold124** [comment]
bruh i was told to do it by one of the staff members, i assumed that if it was already an issue he would've known

**Comment by Cherkir** [comment]
closing this as it's a duplicate
