### ISSUE TITLE
Hard suits should be a little more protective against aliens mulching your head.

### ISSUE THREAD

**Issue by Toweringdarkness** [Cherkir/Alien-Isolation-13#43]
After once again having been killed by a alien, that had me pinned to the ground and then proceeded in two seconds flat to kill me by destroying my head. I feel as if there should be a little more perfection afforded to people in hard suits. 

Like preventing the near instant kill they can do when you have your suit and helmet fully extended. 

Perfectly fine with still being pinned to the ground and it slashing my face and body to ribbons but I would like time to properly react and scream horribly while it's going on.

**Comment by BusCoder** [comment]
Fixed. Close this.
