### ISSUE TITLE
Can't put hollow bullets back into M4A1

### ISSUE THREAD

**Issue by MrJJJ2** [Cherkir/Alien-Isolation-13#53]
Step 1. Try to apply back the hollow bullets you ejected from M4A1 magazine
Step 2. Wonder why you can't re-apply M4A1 starting hollow-point magazine

**Comment by BusCoder** [comment]
It would be more helpful on which Hollow point mag. You were talking about since there is you know, like 700 of them.

**Comment by WarlordToby** [comment]
He is talking about /obj/item/ammo_magazine/m4/brute i assume
M4's use only one ammo type

**Comment by MrJJJ2** [comment]
> It would be more helpful on which Hollow point mag. You were talking about since there is you know, like 700 of them.

I could have sworn i specified
Basically, in a gun vendor, there is a gun called M4A1 Semi-Automatic Rifle, when you vend it, it spawns with /obj/item/ammo_magazine/m4/brute inside of it, if you unload the /obj/item/ammo_magazine/m4/brute, you can't load it back in, but you can load in /obj/item/ammo_magazine/m4/rubber

**Comment by BusCoder** [comment]
should be fixed soon, sorry for the wait.

**Comment by BusCoder** [comment]
Warlord toby that is wrong, since the m4 also uses rubber bullets. it's fixed anyways have fun!
