### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by Greenpoison** [Cherkir/Alien-Isolation-13#87]
Said it in the title, html needs discord link updated.

**Comment by Cherkir** [comment]
it works fine for me

**Comment by Greenpoison** [comment]
Odd, https://discord.gg/3aTsW shows as expired for me.

**Comment by Cherkir** [comment]
oh, wasn't aware you meant the one in the MOTD

**Comment by Cherkir** [comment]
fixed
